import { Tree } from "./Tree.js";
const tree = new Tree([1, 7, 4, 23, 8, 9, 4, 3, 5, 7, 9, 67, 6345, 324]);

tree.insert(17);
tree.insert(0);
tree.insert(18);
tree.insert(16);
tree.insert(325);
tree.insert(327);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(4);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(67);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(8);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(9);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(23);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(5);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(324);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.deleteItem(6345);
tree.prettyPrint(tree.root);
console.log("==========================================");
