import { Tree } from "./Tree.js";
// const tree = new Tree([1, 7, 4, 23, 8, 9, 4, 3, 5, 7, 9, 67, 6345, 324]);
const tree = new Tree([4, 23, 8, 9, 4, 5, 9, 67, 6345, 324]);

// tree.insert(17);
// tree.insert(0);
// tree.insert(18);
// tree.insert(16);
// tree.insert(325);
// tree.insert(327);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(4);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(67);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(8);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(9);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(23);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(5);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(324);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete2(6345);
tree.prettyPrint(tree.root);
console.log("==========================================");
