import { Tree } from "./Tree.js";
const tree = new Tree([1, 7, 4, 23, 8, 9, 4, 3, 5, 7, 9, 67, 6345, 324]);

tree.insert(17);
tree.insert(0);
tree.insert(18);
tree.insert(16);
tree.insert(325);
tree.insert(327);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(4);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(67);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(8);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(9);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(23);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(5);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(324);
tree.prettyPrint(tree.root);
console.log("==========================================");
tree.delete(6345);
tree.prettyPrint(tree.root);
console.log("==========================================");
